name: Matrix bug

on:
  workflow_dispatch:

jobs:
  loop_matrix:
    strategy:
      matrix:
        index: [0,1,2,3]
    uses: ./.github/workflows/reusable.yml

  on-failure:
    needs: loop_matrix
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Failed!"
      
  final_job:
    name: Final step
    runs-on: ubuntu-latest
    needs: [loop_matrix]
    if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Test
        run: |
          echo "needs.loop_matrix.result ${{ needs.loop_matrix.result }}"
          echo "needs.*.result cancelled ${{ contains(needs.*.result, 'cancelled') }}"
          echo "needs.*.result failure ${{ contains(needs.*.result, 'failure') }}"
