name: Matrix bug

on:
  workflow_dispatch:

jobs:
  loop_matrix:
    strategy:
      matrix:
        index: [0,1,2,3]
    uses: ./.github/workflows/reusable.yml

  on-failure:
    needs: loop_matrix
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Failed!"

  on-success:
    needs: loop_matrix
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Success!"

  on-cancelled:
    needs: loop_matrix
    if: cancelled()
    runs-on: ubuntu-latest
    steps:
      - run: echo "Cancelled!"

  final_job:
    name: Final step
    runs-on: ubuntu-latest
    needs: [loop_matrix]
    if: always()
    # if: ${{ !cancelled() && !failure() }}
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Dump needs context
        env:
          NEEDS_CONTEXT: ${{ toJson(needs) }}
        run: echo "$NEEDS_CONTEXT"        
      # - name: Dump strategy context
      #   env:
      #     STRATEGY_CONTEXT: ${{ toJson(strategy) }}
      #   run: echo "$STRATEGY_CONTEXT"
      # - name: Dump matrix context
      #   env:
      #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
      #   run: echo "$MATRIX_CONTEXT"

      - name: Show default environment variables
        run: |
          echo "The job_id is: $GITHUB_JOB"   # reference the default environment variables
          echo "The id of this action is: $GITHUB_ACTION"   # reference the default environment variables
          echo "The run id is: $GITHUB_RUN_ID"
          echo "The GitHub Actor's username is: $GITHUB_ACTOR"
          echo "GitHub SHA: $GITHUB_SHA"      
      - name: Test
        run: |
          echo "needs.loop_matrix.result ${{ needs.loop_matrix.result }}"
          echo "needs.*.result cancelled ${{ contains(needs.*.result, 'cancelled') }}"
          echo "needs.*.result failure ${{ contains(needs.*.result, 'failure') }}"
