name: Reusable

on:
  workflow_call:

jobs:
  test:
    name: Reusable
    runs-on: ubuntu-latest
    
    steps:
      - name: toss a coin
        run: |
          echo "Sleeping..."
          sleep 5
          test=$(shuf -e true false -n 1)
          if [ "$test" = "true" ]; then
              echo "fail" >&2
              exit 1
          else
            echo "success"
          fi

